apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/quotes-backend

namespace: backend

images:
  - name: thabelo/quotes-backend
    newTag: v0.1.0

replicas:
  - name: quotes-backend
    count: 1

