resources:
  - ../../../base/quotes-backend

namePrefix: prod-

namespace: prod

images:
  - name: thabelo/quotes-backend
    newTag: v0.1.0

replicas:
  - name: quotes-backend
    count: 3