---
resources:
- ../../../base/quotes-frontend

namePrefix: dev-

namespace: dev

images:
  - name: thabelo/quotes-frontend
    newTag: latest

replicas:
  - name: quotes-frontend
    count: 1