apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/quotes-frontend

namePrefix: dev-
namespace: dev

images:
  - name: thabelo/quotes-frontend
    newTag: v0.1.0

replicas:
  - name: quotes-frontend
    count: 1

patches:
  - patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: dev.quotes.com
    target:
      kind: Ingress
      name: quotes-ingress