apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: arbitrary

resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  
commonLabels:
  app: quotes-app

images:
- name: thabelo/quotes-backend
  newTag: v0.1.0 

